### ISSUE TITLE
0.16.17 release regression test failure

### ISSUE THREAD

**Issue by chenrui333** [cilium/cilium-cli#2795]
👋 seeing some regression test failure with 0.16.17 build

```
$ /opt/homebrew/Cellar/cilium-cli/0.16.17/bin/cilium install
strconv.ParseUint: parsing "": invalid syntax
```

relates to https://github.com/Homebrew/homebrew-core/pull/189650
full build log, https://github.com/Homebrew/homebrew-core/actions/runs/10857969003/job/30135351920?pr=189650

**Comment by kpryu6** [comment]
me too
```bash
$ curl -LO https://github.com/cilium/cilium-cli/releases/download/v0.16.17/cilium-linux-arm64.tar.gz

$ sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin

$ cilium install
strconv.ParseUint: parsing "": invalid syntax

```

**Comment by OMikkel** [comment]
Experiencing the same

**Comment by michi-covalent** [comment]
thank you for reporting the issue. it's fixed in https://github.com/cilium/cilium-cli/releases/tag/v0.16.18 🙏

**Comment by chenrui333** [comment]
- @michi-covalent still seeing the same in https://github.com/Homebrew/homebrew-core/pull/191299

**Comment by michi-covalent** [comment]
hmm that's strange. could you post the output from `cilium version` and `cilium install` commands? it looks like this in my env:

```
% cilium version
cilium-cli: v0.16.18 compiled with go1.23.1 on linux/amd64
cilium image (default): v1.16.1
cilium image (stable): v1.16.1
cilium image (running): unknown. Unable to obtain cilium version. Reason: release: not found
```
```
% cilium install
🔮 Auto-detected Kubernetes kind: kind
✨ Running "kind" validation checks
✅ Detected kind version "0.20.0"
ℹ️  Using Cilium version 1.16.1
🔮 Auto-detected cluster name: kind-kind
🔮 Auto-detected kube-proxy has been installed
```

**Comment by michi-covalent** [comment]
ah i think i know what's going on. the formula needs to be updated to pass this additional flag: https://github.com/cilium/cilium-cli/blame/b4a467c5c5941c76fac6806c41cce2ea03f6c9b2/Makefile#L18

https://github.com/Homebrew/homebrew-core/blob/2b99a9f9b89b400fa793973f7b51c2c573c19f44/Formula/c/cilium-cli.rb#L29-L34

**Comment by chenrui333** [comment]
I see, doing the change now 👍
