### ISSUE TITLE
`cilium hubble port-forward` broken if Cilium was installed via Helm

### ISSUE THREAD

**Issue by gandro** [cilium/cilium-cli#904]
## Bug report

**General Information**

- Cilium CLI version (run `cilium version`): `cilium-cli: v0.11.7 compiled with go1.18.2 on linux/amd64`

**How to reproduce the issue**

1. Install Cilium via Helm (not Cilium-CLI) with Hubble Relay
2. Try to use `cilium hubble port-forward`. It fails with the following error:
```
cilium hubble port-forward
Unable to parse the provided version "", assuming v1.11.5 for ConfigMap compatibility

Error: Unable to port forward: unable to retrieve helm values secret kube-system/cilium-cli-helm-values: secrets "cilium-cli-helm-values" not found
```

This used to work before we switched the internals to use Helm, so this is a *regression*.
There is no reason why we shouldn't be able to port-forward if Cilium was installed via Helm.

**Comment by gandro** [comment]
Fixed by #928

**Comment by yeahservice** [comment]
I still have this issue with the newest version (also tried `v0.11.9`)
```
cilium hubble port-forward&
[1] 244624

Error: Unable to port forward: unable to retrieve helm values secret kube-system/cilium-cli-helm-values: secrets "cilium-cli-helm-values" not found
``` 

```
cilium version
cilium-cli: v0.11.11 compiled with go1.18.3 on linux/amd64
cilium image (default): v1.11.6
cilium image (stable): v1.11.6
cilium image (running): v1.11.6
```

**Comment by patrickpichler** [comment]
I took the liberty to investigate the issue and submit a PR which fixes it.
